spring.application.name=spring-ai-demo
spring.profiles.active=dev

# OpenAI
spring.ai.chat.client.enabled=false
spring.ai.openai.base-url=https://ark.cn-beijing.volces.com/api
spring.ai.openai.api-key=xxx
spring.ai.openai.chat.options.model=doubao-seed-2-0-pro-260215
spring.ai.openai.chat.options.reasoning-effort=low
spring.ai.openai.chat.completions-path=/v3/chat/completions
spring.ai.retry.max-attempts=3
spring.ai.retry.on-client-errors=false

logging.level.root=info
logging.level.org.springframework.ai=debug