spring.application.name=spring-ai-demo
spring.profiles.active=dev

# OpenAI
spring.ai.chat.client.enabled=false
spring.ai.openai.base-url=https://ark.cn-beijing.volces.com/api
spring.ai.openai.api-key=xxx
spring.ai.openai.chat.options.model=doubao-seed-2-0-pro-260215
spring.ai.openai.chat.options.reasoning-effort=low
spring.ai.openai.chat.completions-path=/v3/chat/completions
spring.ai.retry.max-attempts=3
spring.ai.retry.on-client-errors=false

spring.ai.mcp.server.streamable-http.mcp-endpoint=/api/v1/mcp
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.protocol=streamable

# ChatMemory MongoDB
spring.ai.chat.memory.repository.mongo.create-indices=false
spring.ai.chat.memory.repository.mongo.ttl=0
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=spring-ai
spring.data.mongodb.username=root
spring.data.mongodb.password=<PASSWORD>

# Tavily Search API
spring.ai.tavily.api-key=your-tavily-api-key

logging.level.root=info
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG