server.port=8081
spring.application.name=ai-alibaba-demo
spring.main.web-application-type=none

# OpenAI (兼容火山引擎豆包)
spring.ai.openai.base-url=https://ark.cn-beijing.volces.com/api
spring.ai.openai.api-key=xxx
spring.ai.openai.chat.options.model=doubao-seed-2-0-pro-260215
spring.ai.openai.chat.options.reasoning-effort=low
spring.ai.openai.chat.completions-path=/v3/chat/completions
spring.ai.retry.max-attempts=3
spring.ai.retry.on-client-errors=false
spring.profiles.active=dev

logging.level.root=info
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG
